### ISSUE TITLE
Implement image picker during signup

### ISSUE THREAD

**Issue by stephanNorsten** [AEEooTo/pindery#16]
Remember to do a popup for the choose between camera and gallery

**Comment by dedeswim** [comment]
To make the images fit you can try to use this:
```
new Container(
      height: radius, // the radius of the circle
      width: radius,
      child: new Material(
        color: secondary,
        type: MaterialType.circle,
        child: new Image.file(path),
      ),
)
```
Instead of using `CircleAvatar`, even though I read that images should fill automatically.
I did it in the last [commit](https://github.com/AEEooTo/pindery/commit/762f632910e57c974ffe13c4f7c28bf3deab8e3c#diff-0c484b761b58c347135f450ac75092e0R33) for the user images inside the app. In this way I can also use a placeholder and cache the image

**Comment by stephanNorsten** [comment]
Actually right now the app square cuts the profile pictures, but it doesn't tell the user so its not completely ok

**Comment by stephanNorsten** [comment]
Actually the library on github has the `BoxFit.cover` parameter, but I think we will need to wait the next library release or however is it called

**Comment by dedeswim** [comment]
Are you talking about the 
`CircleAvatar` library?
